//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracPlakaSistemi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GirisYapanAraclar
    {
        public string tc_no { get; set; }
        public Nullable<int> kapi_id { get; set; }
        public string plaka { get; set; }
        public System.DateTime date { get; set; }
        public int id { get; set; }
    
        public virtual GirisKapilari GirisKapilari { get; set; }
    }
}
