//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracPlakaSistemi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlakaGorsel
    {
        public int Id { get; set; }
        public Nullable<int> PlakaId { get; set; }
        public string PathName { get; set; }
    
        public virtual KayitliAraclar KayitliAraclar { get; set; }
    }
}
