//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracPlakaSistemi.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MisafirAraclar
    {
        public int Id { get; set; }
        public string tc_no { get; set; }
        public string plaka { get; set; }
        public string arac_marka { get; set; }
        public System.DateTime date { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
    }
}
