//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracPlakaSistemi.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AracPlakaSistemiEntities : DbContext
    {
        public AracPlakaSistemiEntities()
            : base("name=AracPlakaSistemiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GirisKapilari> GirisKapilari { get; set; }
        public virtual DbSet<GirisYapanAraclar> GirisYapanAraclar { get; set; }
        public virtual DbSet<KaraListeAraclar> KaraListeAraclar { get; set; }
        public virtual DbSet<KayitliAraclar> KayitliAraclar { get; set; }
        public virtual DbSet<Kisi> Kisi { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<MisafirAraclar> MisafirAraclar { get; set; }
        public virtual DbSet<PlakaGorsel> PlakaGorsel { get; set; }
    }
}
